/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.joao.frame;

import br.com.joao.objeto.Aluno;
import br.com.joao.objeto.TipoAvaliacao;
import java.awt.Panel;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPALuno = new javax.swing.JPanel();
        jLALuno = new javax.swing.JLabel();
        jLMatricula = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jTFMatricula = new javax.swing.JTextField();
        jTFNome = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();
        jPDisiciplina = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLNotas = new javax.swing.JLabel();
        jLN1 = new javax.swing.JLabel();
        jTFN1 = new javax.swing.JTextField();
        jLN2 = new javax.swing.JLabel();
        jLN3 = new javax.swing.JLabel();
        jLN4 = new javax.swing.JLabel();
        jTFN2 = new javax.swing.JTextField();
        jTFN3 = new javax.swing.JTextField();
        jTFn4 = new javax.swing.JTextField();
        jBCalcular = new javax.swing.JButton();
        jLDisciplina = new javax.swing.JLabel();
        jTFDisciplina = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPALuno.setBackground(new java.awt.Color(102, 204, 255));
        jPALuno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0)));

        jLALuno.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLALuno.setText("Aluno");

        jLMatricula.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLMatricula.setText("Matrícula");

        jLNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLNome.setText("Nome");

        jTFMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFMatriculaActionPerformed(evt);
            }
        });

        jBCadastrar.setBackground(new java.awt.Color(255, 204, 204));
        jBCadastrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPALunoLayout = new javax.swing.GroupLayout(jPALuno);
        jPALuno.setLayout(jPALunoLayout);
        jPALunoLayout.setHorizontalGroup(
            jPALunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPALunoLayout.createSequentialGroup()
                .addGroup(jPALunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPALunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPALunoLayout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jLALuno))
                        .addGroup(jPALunoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLMatricula))
                        .addGroup(jPALunoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTFMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                        .addGroup(jPALunoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLNome))
                        .addGroup(jPALunoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTFNome)))
                    .addGroup(jPALunoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jBCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPALunoLayout.setVerticalGroup(
            jPALunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPALunoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLALuno)
                .addGap(39, 39, 39)
                .addComponent(jLMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        jPDisiciplina.setBackground(new java.awt.Color(153, 204, 255));
        jPDisiciplina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0)));

        jLNotas.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLNotas.setText("Notas");

        jLN1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLN1.setText("N1");

        jLN2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLN2.setText("N2");

        jLN3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLN3.setText("N3");

        jLN4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLN4.setText("N4");

        jTFN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFN3ActionPerformed(evt);
            }
        });

        jBCalcular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBCalcular.setText("Calcular");
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        jLDisciplina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLDisciplina.setText("Nome da Disciplina");

        jTFDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDisciplinaActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(102, 0, 102));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione uma das opções abaixo>", "Trabalho", "Prova", "Seminário" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPDisiciplinaLayout = new javax.swing.GroupLayout(jPDisiciplina);
        jPDisiciplina.setLayout(jPDisiciplinaLayout);
        jPDisiciplinaLayout.setHorizontalGroup(
            jPDisiciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDisiciplinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDisiciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFDisciplina)
                    .addGroup(jPDisiciplinaLayout.createSequentialGroup()
                        .addComponent(jLDisciplina)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPDisiciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDisiciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPDisiciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPDisiciplinaLayout.createSequentialGroup()
                                .addComponent(jLNotas)
                                .addGap(56, 56, 56))
                            .addGroup(jPDisiciplinaLayout.createSequentialGroup()
                                .addGroup(jPDisiciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLN2)
                                    .addComponent(jLN4)
                                    .addComponent(jLN1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPDisiciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFN1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFn4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFN2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()))
                        .addGroup(jPDisiciplinaLayout.createSequentialGroup()
                            .addComponent(jLN3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTFN3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDisiciplinaLayout.createSequentialGroup()
                        .addComponent(jBCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jPDisiciplinaLayout.setVerticalGroup(
            jPDisiciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPDisiciplinaLayout.createSequentialGroup()
                .addGroup(jPDisiciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDisiciplinaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLNotas)
                        .addGap(27, 27, 27)
                        .addGroup(jPDisiciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLN1))
                        .addGap(13, 13, 13)
                        .addGroup(jPDisiciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLN2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPDisiciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLN3))
                        .addGap(18, 18, 18)
                        .addGroup(jPDisiciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLN4))
                        .addGap(18, 18, 18)
                        .addComponent(jBCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                    .addGroup(jPDisiciplinaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLDisciplina)
                        .addGap(18, 18, 18)
                        .addComponent(jTFDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPALuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPDisiciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPDisiciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPALuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFN3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFN3ActionPerformed

    private void jTFDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDisciplinaActionPerformed

    private void jTFMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFMatriculaActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        // TODO add your handling code here:
        String nome, disciplina;
        int matricula;
        
        matricula = Integer.parseInt(jTFMatricula.getText());
        nome = jTFNome.getText();
        disciplina = jTFDisciplina.getText();
        
        Aluno a = new Aluno(nome, matricula);
        
        JOptionPane.showMessageDialog(this, a.toString());
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCalcularActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBCalcular;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLALuno;
    private javax.swing.JLabel jLDisciplina;
    private javax.swing.JLabel jLMatricula;
    private javax.swing.JLabel jLN1;
    private javax.swing.JLabel jLN2;
    private javax.swing.JLabel jLN3;
    private javax.swing.JLabel jLN4;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLNotas;
    private javax.swing.JPanel jPALuno;
    private javax.swing.JPanel jPDisiciplina;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTFDisciplina;
    private javax.swing.JTextField jTFMatricula;
    private javax.swing.JTextField jTFN1;
    private javax.swing.JTextField jTFN2;
    private javax.swing.JTextField jTFN3;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFn4;
    // End of variables declaration//GEN-END:variables
}
